### ISSUE TITLE
[Bug]: Status is set to away unless mouse moves over Teams for Linux window.

### ISSUE THREAD

**Issue by JasonRaveling** [IsmaelMartinez/teams-for-linux#1644]
### Can you reproduce this bug in the website/PWA?

Not applicable

### Describe the bug

My status automatically gets set to idle/away (yellow) even when I am actively using my mouse and keyboard. My status only gets set to available (green) when I  move my mouse over Teams for Linux.

### What package are you using?

AppImage on Ubuntu 24.04.2 LTS.

### Version

2.0.4

### Reproduction steps

```markdown
1. Start Teams for Linux AppImage.
2. Use my computer as normal, not hovering over or giving focus to Teams for Linux window.
3. Status goes idle/away (yellow)
4. Move mouse over Teams for Linux window (window focus is not needed) so it detects activity.
```

### Expected Behavior
Teams for Linux previously detected that I was active, regardless of whether or not I was actively using the app or had my mouse over the app.

### Debug

```markdown
No config file found, using default values
all good with customUserDir you aren't using them
all good with clearStorage you aren't using them
Initialising logger with config: "{}"
11:03:20.095 › File logging at /home/username/.config/teams-for-linux/logs/main.log with level silly
11:03:20.097 › Console logging enabled with level silly
11:03:20.097 › Logger initialised
11:03:20.097 › configPath: /home/username/.config/teams-for-linux
11:03:20.097 › configFile: {}
11:03:20.548 › (node:13417) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `teams-for-linux --trace-deprecation ...` to show where the warning was created)
11:03:21.065 › processArgs: [
  '/tmp/.mount_teams-wAWGrw/teams-for-linux',
  '--webDebug',
  '--logConfig={}'
]
11:03:21.066 › testing RegExp processArgs false
11:03:21.067 › testing RegExp processArgs false
11:03:21.067 › testing RegExp processArgs false
11:03:21.067 › Waiting for network...
11:03:21.067 › Testing network using net.request() for https://teams.microsoft.com/v2
11:03:21.069 › Spellchecker is disabled!
11:03:21.983 › Network test successful with method https
11:03:21.984 › Loading initial URL...
[13417:0407/110322.459531:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[13417:0407/110322.459588:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
11:03:23.039 › did-frame-finish-load {} true
11:03:23.040 › did-finish-load
11:03:24.747 › Badge count set to '0'
11:03:24.760 › Badge count set to '0'
11:03:26.746 › did-frame-finish-load {} false
[13417:0407/110326.747320:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[13417:0407/110326.747402:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

```

### Additional context

I have just upgraded from 1.13 to 2.0.4. I cleared storage after I started using 2.0.4.

**Comment by dcobbley** [comment]
I am also experiencing this behavior.

Brand new user as of today, so no cache to clear...
Package: Deb, Ubuntu 24.04, V2.0.4, Chromium 134.0.6998.165 (installed from snap).

**Comment by dcobbley** [comment]
@IsmaelMartinez, was the change to [app/browser/index.js](https://github.com/IsmaelMartinez/teams-for-linux/pull/1638/files#diff-51fd11f9828ad022858c3e612962ef70165978a9a0dc18aea881c178268f5857) intentional?

```
diff --git a/app/browser/index.js b/app/browser/index.js
index b83f311..866e3ff 100644
--- a/app/browser/index.js
+++ b/app/browser/index.js
@@ -1,12 +1,10 @@
 (function () {
   const { ipcRenderer } = require("electron");
-  const ActivityManager = require("./notifications/activityManager");
 
   let config;
   ipcRenderer.invoke("get-config").then((mainConfig) => {
     config = mainConfig;
     initializeModules(config, ipcRenderer);
-    new ActivityManager(ipcRenderer, config).start();
   });
```

It seems this disabled the ActivityManager from starting and therefore `teams2IdleTracker.handleMonitoredWindowEvent();` is no longer being called.

**Comment by 31337-4554551n** [comment]
Having the same issue. Makes things awkward at work.
Appreciate you jumping onto this so quickly

**Comment by IsmaelMartinez** [comment]
Thanks for reporting.

That looks like an overside from my side, and adding back those lines should fix it. I hope to be back home tonight, but if anyone has the time, the contributing.md should have some clear(ISH) instructions on how to add this. 

Apologies for it. Maybe use an older version in the meantime, but hopefully this should be fixed soon.

**Comment by JasonRaveling** [comment]
lol, I guess we are thinking the same thing this morning, @dcobbley. You were just a bit ahead of me :-)

**Comment by Crescent-Saturn** [comment]
Same here, I remember it was like this a while ago. Now with the lastest update, this issue comes back...

**Comment by IsmaelMartinez** [comment]
This should be fixed in https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.0.5 . Thanks for reporting it and finding the reason of why this failed.

**Comment by 31337-4554551n** [comment]
Hi,

I updated the flatpak this morning, restarted teams and the issue persists

**Comment by 31337-4554551n** [comment]
Hi,

Thank you so much for fixing this so quickly.
I was wondering when the flatpak update will be available?

**Comment by IsmaelMartinez** [comment]
@31337-4554551n , flatpak takes a few days and is out of my control. I did merge the release in there. In the meantime either use an older version of use one of the other packages that we provide.

**Comment by 31337-4554551n** [comment]
Oh really, forgive my ignorance. Who controls the flatpak? I thought it was all you

**Comment by IsmaelMartinez** [comment]
Well, well... is a big long story, but the community added support for that package, but then no-one could support it. I do the releases and try to support it, but I don't have a way to test it.

This is independent on who maintains the package. The flatpak release process can take a few days on its own to update each device. It is their way of releasing, not something package maintainers can configure in detail. It is normally 2-12 hours, but I have seen asking people for the version 3-4 days later. Basically, it depends on how busy their servers are.

**Comment by 31337-4554551n** [comment]
Right, so "the community" looks after it.
That definitely makes it tricky in terms of both follow up, and ensuring the flatpak is above board.
I thought I only needed to trust you and your releases, but turns out there's also some shadowy cabal that tinkers with flatpaks in their own time before release.
very confusing.

What do you mean by "each device"? I thought the point of flatpak was to include everything needed so it could run on anything?

**Comment by IsmaelMartinez** [comment]
I do push the releases there, but they manage how to update each of you. Is the same for each package flatpak supports. 

There are more than half a million devices using teams-for-linux in flatpak alone, so it takes a bit of time to send the update to all of them. If you are lucky, you are one of the first on the list, if not, you might need to wait a bit.

**Comment by 31337-4554551n** [comment]
Now I'm very confused. I didn't realise they send updates, so much as users run queries against flathub and if the version there is newer they pull it down. At least that's how I thought it works. Check the OS app store which checks flathub, pulls down an update if any

**Comment by IsmaelMartinez** [comment]
hey, don't take my words on it. I don't work at flatpak nor have a lot of experience on it. Probably ask on their community if you need specifics on how it works. I just mention what users have reported. Maybe when your computer queries for the new version, it hasn't propagated to all servers they have. Again, just an assumption. I do publish the new version and trigger the build, I just mention what users do report.

**Comment by 31337-4554551n** [comment]
I do appreciate your time. Thank you again for all your hard work!

**Comment by 31337-4554551n** [comment]
I realise this is also not the place to ask, but while I have you:
There is a fork of your project called Outlook for Linux. Hasn't been updated in 2 years. Was delisted off flathub last November.

Would you have any interest in doing you own version of Outlook for Linux alongside teams?

**Comment by IsmaelMartinez** [comment]
Hi @31337-4554551n, I am not related to that project and I don't wish to support it. Feel free to support it on your own time and/or contact the person that used to maintain it.
