### ISSUE TITLE
[Bug]: Zoom from systray menu not working, Two finger pinching on touchpad does.

### ISSUE THREAD

**Issue by sergiocallegari** [IsmaelMartinez/teams-for-linux#1789]
### Can you reproduce this bug in the website/PWA?

Not applicable

### Describe the bug

Using zoom (in; out; to actual size) from the systray menu does nothing.

### What package are you using?

flatpak

### Version

2.1.3

### Reproduction steps

```markdown
1. Start application
2. Go to some chat
3. Try to enlarge/reduce the font size by zooming with the systray menu
```

### Expected Behavior

```markdown
The same thing that happens by using the two finger zoom on the touchpad should happen. But nothing happens.
```

### Debug

```markdown

```

### Additional context

Unclear what reproducing on PWA is.

**Comment by IsmaelMartinez** [comment]
Hi @sergiocallegari , thanks for reporting.

Flatpak can do strange things, can you check with another packaging option and provide some logs? 

Without logs I can only guess what might be happening in your system, and normally that is not the best course of action. 

Can you also verify if you can use the shortcuts (using the Super Key + or Super Key -)

Thanks again

**Comment by IsmaelMartinez** [comment]
closing as I suspect this was broken a few weeks ago, but it should be now fixed in [2.5.0](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.5.0)

**Comment by FranzXaver** [comment]
This is still not working in 2.5.0, I used to be able to zoom using Ctrl+Mouse-Wheel or Ctrl-+

**Comment by IsmaelMartinez** [comment]
yes, my mistake. I thought I did fix it in there, but clearly not. Thanks for getting back. Hopefully 2.5.2 will fix it

**Comment by IsmaelMartinez** [comment]
Hi, can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.5.2 ? Thanks!

**Comment by FranzXaver** [comment]
Thanks, 2.5.2 fixed this issue for me.

**Comment by IsmaelMartinez** [comment]
I will close it. I will wait a few days until I merge it in main and then it creates a flatpak release. Thanks for checking and glad it is working!
