### ISSUE TITLE
Blank screen on startup, removing ~/.config/teams-for-linux doesn't help

### ISSUE THREAD

**Issue by bremner** [IsmaelMartinez/teams-for-linux#339]
**Describe the bug**

I hesitate to report a "known issue", but I don't completely understand the mention of "on login".
In case that is different than "on startup", here is my report.

Initially I get just the icon in the status bar, but if I right click that and click run, I get a blank window titled "teams-for-linux".

Installing the snap with "snap install --channel=edge teams-for-linux" seems to work, although I don't know if that is built from the same source.

What's different?
1) I don't make it as far as a login screen
2) Removing ~/.config/teams-for-linux does not change anything.

**To Reproduce**
1. git checkout d7f3647ad30161
2. sudo apt install yarnpkg rpm
3. yarnpkg run dist:linux
3.  start teams-for-linux, e.g. with "yarnpkg start"
4. Right click on icon, select "open"
5. see blank screen.

**Expected behavior**
I expect to see the teams login box

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Installation package: source
 - Version:  d7f3647ad30161

**Additional context**

yarnpkg is probably called yarn other places

I'm running the tiling window manager i3

**Comment by IsmaelMartinez** [comment]
Hi @bremner,

If you are running from source, the folder to remove is slightly different and depends on your system.

Its normally called `~/.config/Electron/`

**Comment by IsmaelMartinez** [comment]
also, yeah, it should be the same version. Travis is giving me a headache and snapcraft are ignoring me but edge has now d7f3647

**Comment by bremner** [comment]
IsmaelMartinez <notifications@github.com> writes:

> Hi @bremner,
>
> If you are running from source, the folder to remove is slightly different and depends on your system.
>
> Its normally called `~/.config/Electron/`

Thanks for the information. I confirmed that ~/.config/Electron is
created by

% yarnpkg start

Unfortunately removing that directory does not seem to change anything;
the window is still blank.

**Comment by IsmaelMartinez** [comment]
can you try if the "master" branch works? That is the same one as if you use snap stable branch. Ta

**Comment by bremner** [comment]
IsmaelMartinez <notifications@github.com> writes:

> can you try if the "master" branch works? That is the same one as if you use snap stable branch. Ta
>

Seems to be exactly the same. Stable snap works, at least as far as
getting to the MS Sign in box, but self-compiled version just gives a
blank window. It seems logical that there is something about my build
environment that is breaking things. In case it's helpful I attach
"yarn.lock", which I guess has all the package versions in it

d

**Comment by IsmaelMartinez** [comment]
Not that I will recommend it for using always but, have you tried using
sudo? Sorry if you have already tried that. In the mobile...

**Comment by bremner** [comment]
IsmaelMartinez <notifications@github.com> writes:

> Not that I will recommend it for using always but, have you tried using
> sudo? Sorry if you have already tried that. In the mobile...

I don't even get a status bar ico or window as root.

```
        convex# ./teams-for-linux 
        configPath = /root/.config/teams-for-linux
        Failed to get the config file, using default values
        configFile = {}
        processArgs [ '/home/bremner/software/upstream/teams-for-linux/dist/linux-unpacked/teams-for-linux' ]

        (teams-for-linux:2063226): libappindicator-WARNING **: 12:36:17.904: Unable to get the session bus: Unknown or unsupported transport “disabled” for address “disabled:”

        (teams-for-linux:2063226): LIBDBUSMENU-GLIB-WARNING **: 12:36:17.904: Unable to get session bus: Unknown or unsupported transport “disabled” for address “disabled:”
        ^R
        ^Cbefore-quit
        window close
        ^C
```

**Comment by IsmaelMartinez** [comment]
Have you tried just using yarn instead of yarnpkg? Not sure if there is a difference on them

**Comment by bremner** [comment]
IsmaelMartinez <notifications@github.com> writes:

> Have you tried just using yarn instead of yarnpkg? Not sure if there is a difference on them
>

As far as I know, yarnpkg is just the debian name for yarn (to avoid
conflicts). But I tried

        ./node_modules/yarn/bin/yarn start

and it does not seem make a difference

**Comment by IsmaelMartinez** [comment]
Can you put the yarnpkg version? It's pretty strange but I suspect it might be an older version of yarn.

**Comment by bremner** [comment]
IsmaelMartinez <notifications@github.com> writes:

> Can you put the yarnpkg version? It's pretty strange but I suspect it might be an older version of yarn.
>

╭─ convex:~/software/upstream/teams-for-linux 
╰─ (git)-[develop]-% yarnpkg --version             
1.22.4

╭─ convex:~/software/upstream/teams-for-linux 
╰─ (git)-[develop]-% ./node_modules/yarn/bin/yarn --version
1.22.0

I.e. the debian version is actually a bit newer.

BUT, the strangest thing is without knowing what changed, it seems both
running from source, linux/unpacked, aand the debian packages all seem
to work now. This machine is tracking debian testing, so it's possible
something being upgraded fixed things. The good news is that I think you
can close this bug. The bad news is that I don't know how to help
someone else with these symptoms, except maybe checking kernel logs for
something interesting, as the kernel is one of the things that updated
today.

Thanks for the effort you put in on this bug (and for maintaining
teams-for-linux).

d

**Comment by IsmaelMartinez** [comment]
glad that is fixed, intrigued that we will probably never know what was wrong. Cheers!

**Comment by bremner** [comment]
The issue is back for me. I have have (old) self-built .deb and app-images for 1.02 that work, and (new) 1.05 and 1.06 that exhibit the blank white screen behaviour. I wanted to try rebuilding v1.0.2 with my current toolchain, but I can't find a tag for it. Looking at the looks it looks like that should be d7f3647ad30, does that sound right?

**Comment by IsmaelMartinez** [comment]
have you tried with the packaged versions that I provide now in here? Added multiple architectures in 1.0.5 when I moved from Travis to github actions 
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.5

**Comment by bremner** [comment]
IsmaelMartinez <notifications@github.com> writes:

> have you tried with the packaged versions that I provide now in here?
> Added multiple architectures in 1.0.5 when I moved from Travis to
> github actions
> https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.5
>

Yes, your app image for 1.0.5 also works. Are the build logs available
somewhere? Maybe I'll try to tease out what the difference in the build
environment is.

**Comment by IsmaelMartinez** [comment]
Added the logs in here:

[logs_70.zip](https://github.com/IsmaelMartinez/teams-for-linux/files/4968952/logs_70.zip)

Just using github actions so the configuration is here:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/.github/workflows/build.yml

Not sure if I can help any much. That should give you enough to play around. Hope you find your tool-chain shenanigans issue!
