### ISSUE TITLE
Prevent screensaver while in a call

### ISSUE THREAD

**Issue by FloEdelmann** [IsmaelMartinez/teams-for-linux#613]
**Is your feature request related to a problem? Please describe.**
When I'm in a call, I often do not move the mouse or tap the keyboard for a long time. After 5 minutes (OS setting), the screensaver kicks in, which is annoying.

**Describe the solution you'd like**
Prevent screensaver/standby while in a call.

**Describe alternatives you've considered**
Manually moving my mouse, but that's not a practical solution.

**Additional context**
It is working in the official Teams client.
It might be that this is already implemented in teams-for-linux and just not working for me. I'm using Kubuntu 22.04 with KDE Plasma 5.25.5.

**Comment by jijojosephk** [comment]
@FloEdelmann which package did you use to install?

**Comment by jijojosephk** [comment]
This issue has been fixed. github releases (pre-release `1.0.43`) will be available soon.

**Comment by FloEdelmann** [comment]
I'm using the Flatpak version from Flathub. Thanks for fixing this so quickly! I'll give it a try in the released version and will report if it's not fixed for me.

**Comment by jijojosephk** [comment]
Fixed in `1.0.43`

**Comment by jijojosephk** [comment]
Re-open if it's not fixed.

**Comment by FloEdelmann** [comment]
Unfortunately, the problem still persists for me.

<details>
<summary>System details</summary>

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-48-generic (64-bit)
Graphics Platform: X11

</details>

**Comment by jijojosephk** [comment]
@FloEdelmann which screensaver you have? My development setup is Ubuntu Budgie 22.04 LTS. I had tested with the default screen dimming after a while. We'll try to figure out. No bugs can escape :smile:

**Comment by FloEdelmann** [comment]
I'm using the default of Kubuntu / KDE, KScreenLocker: https://invent.kde.org/plasma/kscreenlocker

**Comment by FloEdelmann** [comment]
@jijojosephk Is there something that I can do to debug this issue? It still persists for me.

**Comment by IsmaelMartinez** [comment]
Try adding --appLogLevels and passing and array of log levels you want to see. @jijojosephk might be more helpful on that area as he introduced that logger, but I think that should do it. The config folder /options should give you a wee bit more info on what log levels are valid

**Comment by geckolinux** [comment]
> Unfortunately, the problem still persists for me in teams-for-linux v1.0.44 Flatpak.

Same for me, teams-for-linux 1.0.52 Flatpak.
Debian GNU/Linux 11 bullseye (x86-64)
Cinnamon 4.8.6 on X11

I'd be glad to attach logs if needed.

**Comment by FloEdelmann** [comment]
Thanks @IsmaelMartinez for the hint. I now tried `--appLogLevels error,warn,info,debug` and it shows these lines in the output (right before and after a call), but the screen saver is not inhibited:

```
[DEBUG] Power save is disabled.
[DEBUG] Power save is restored
```

Should I create a new issue for that?

**Comment by jijojosephk** [comment]
@FloEdelmann the code uses electron's native api. I wonder why it's not working. Does [this](https://bbs.archlinux.org/viewtopic.php?id=140627) mean the problem is with KScreenLocker? It has something to do with dbus.

**Comment by geckolinux** [comment]
@jijojosephk That's what I initially thought too, because normally an Electron app or the Chromium browser inhibits the screensaver while a Youtube video is running or whatever. But in my case I'm on Cinnamon and it's also not inhibiting the screensaver.

I wonder if it has something to do with the Flatpack portal permissions? Although I was also using the official MS Teams Electron app from Flathub and it did inhibit the screensaver during calls.

**Comment by FloEdelmann** [comment]
@jijojosephk I don't think this issue is related to the link you posted, since that concerns KDE 4 (instead of KDE 5) and is already 11 years old.

There seems to be a problem with Electron's `powerSaveBlocker` API on different platforms, although it was not described in more detail: https://github.com/electron/electron/issues/10212#issuecomment-1326551343

Maybe an upgrade to the very latest Electron version already helps? Flatpak permissions also sound like they could be related somehow.

**Comment by jijojosephk** [comment]
Upgrading to electron `22` will break system tray icon. I still don't know what is causing that.

**Comment by geckolinux** [comment]
In Flatseal I can see that `socket=session-bus` is disabled by default for IsmaelMartinez/teams-for-linux , but it's also disabled for the official (deprecated) MS Teams for Linux Flatpak.

**Comment by jijojosephk** [comment]
Electron's API is not working. Don't know what's alternative.

**Comment by jijojosephk** [comment]
I'll try something. Re-opening now.

**Comment by jijojosephk** [comment]
To fix this only we're depend on [this](https://developer.chrome.com/blog/new-in-chrome-79/#wake-lock) chrome API. I've done some changes in `1.0.59`.

**Comment by jijojosephk** [comment]
flatpak version does not work. Some permission might be needed for flatpak.

**Comment by jijojosephk** [comment]
It appears that this permission (flatpak) is needed for this to work. Also it reveals that the previous implementation with [powerSaveBlocker](https://www.electronjs.org/docs/latest/api/power-save-blocker) was also working. @FloEdelmann adn @geckolinux can you check that?

![image](https://user-images.githubusercontent.com/11662148/231044286-89776baf-69a0-47fc-b45e-4ede04c1d0b8.png)

**Comment by geckolinux** [comment]
@jijojosephk Thanks for looking into this. The former official MS Teams Electron app for Linux inhibited the screensaver without any Dbus permissions in Flatseal. But I'll give it a try with [this](https://user-images.githubusercontent.com/11662148/231044286-89776baf-69a0-47fc-b45e-4ede04c1d0b8.png) enabled and I'll let you know.

**Comment by jijojosephk** [comment]
session-bus is a more wider setting. I've updated the flatpak configurations with these.
`
--talk-name=org.freedesktop.PowerManagement
--talk-name=org.gnome.SessionManager
`
flatpak version `1.0.59-2` will have these by default. Once the build is available, you can reset all the permissions for the app. And it should be working.

**Comment by FloEdelmann** [comment]
I tried the same with v1.0.59-2, but the screensaver still kicks in after a few minutes while in a call :slightly_frowning_face:

**Comment by jijojosephk** [comment]
@FloEdelmann I guess, on KDE we may have to have additional talks alogn with `--talk-name=org.freedesktop.PowerManagement --talk-name=org.gnome.SessionManager` .

Can you run `flatpak run --log-session-bus com.github.IsmaelMartinez.teams_for_linux` from terminal and see what happens as soon as the the call gets connected? if anything related to KDE, we can add it to flatpak config. But if the problem is not related to any package (flatpak, deb, appImage) , then either electron's api is not able to inhibit screenlock in KDE or something else we have not discovered yet.

**Comment by jijojosephk** [comment]
Looks fine. Those are basically electron api sending the request to inhibit. But somehow it's not working for you. We need to see if chromium wake lock API does the job.

**Comment by jijojosephk** [comment]
https://developer.chrome.com/blog/new-in-chrome-79/#wake-lock

**Comment by jijojosephk** [comment]
@FloEdelmann there's a new test build for flatpak.
`flatpak install --user https://dl.flathub.org/build-repo/17679/com.github.IsmaelMartinez.teams_for_linux.flatpakref`

From terminal run:

`flatpak run --log-session-bus com.github.IsmaelMartinez.teams_for_linux --appLogLevels debug --screenLockInhibitionMethod WakeLockSentinel`

**Comment by FloEdelmann** [comment]
The test build can't be downloaded anymore. I tried with v1.0.68 (flatpak), and found these lines in the log:

```
C29: -> org.freedesktop.PowerManagement call org.freedesktop.PowerManagement.Inhibit.Inhibit at /org/freedesktop/PowerManagement/Inhibit
B2659: <- :1.21 return from C29
[DEBUG] Power save is disabled using WakeLockSentinel API.
```

```
B27: <- org.freedesktop.DBus return from C26
C27: -> org.freedesktop.DBus call org.freedesktop.DBus.NameHasOwner at /org/freedesktop/DBus
B28: <- org.freedesktop.DBus return from C27
C28: -> org.freedesktop.DBus call org.freedesktop.DBus.NameHasOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.freedesktop.ScreenSaver, policy: 0 (required 1)
B29: <- (no sender) return from C28
*REWRITTEN*
C29: -> org.freedesktop.DBus call org.freedesktop.DBus.NameHasOwner at /org/freedesktop/DBus
B30: <- org.freedesktop.DBus return from C29
```

However, the screensaver still is not disabled...

**Comment by jijojosephk** [comment]
If you use the default method also, the logs are same?

**Comment by FloEdelmann** [comment]
No, using the default method, I don't get the "Power save is disabled using …" line.

Also, I just noticed that during a call, there are several occasions in the log where "UnInhibit" is called just after (no to maybe only a few log lines in between) the "Inhibit" call. Maybe the "Teams call end" event is triggered to early sometimes?

**Comment by jijojosephk** [comment]
I'm not familiar with flatpak run command line permissions, if you have flatseal installed you can choose teams-for-linux and add talk `org.freedesktop.ScreenSaver` and restart teams and see.

**Comment by jijojosephk** [comment]
@FloEdelmann can you confirm?

**Comment by FloEdelmann** [comment]
I'll try it.

**Comment by FloEdelmann** [comment]
Adding the `org.freedesktop.ScreenSaver` "talk" permission in Flatseal and then running with `--screenLockInhibitionMethod WakeLockSentinel` seems to work fine! :slightly_smiling_face:

**Comment by jijojosephk** [comment]
Closing this as the permissions seems to work. Also latest versions comes with these permissions by default.
