### ISSUE TITLE
Screen sharing proportions (21:9 while sharing 16:9)

### ISSUE THREAD

**Issue by abobowicz** [IsmaelMartinez/teams-for-linux#912]
**Describe the bug**
I have 2 screens, each with different proportions (16:9 and 21:9). When I have the teams window on my widescreen and I want to share my 16:9 it shares it while keeping the 21:9 proportions (cutting the top and bottom of sharing screen), but when I put the teams window on my 16:9 screen and start sharing it works fine. What's more, when I share my 21:9 while the teams window is on my 16:9 it also works fine. 
This problem persists even if I share only a single window on 16:9 while teams is on 21:9.

**To Reproduce**
1. You need 2 diffrent proportions screen
2. Start sharing one of them while teams window is on different screen (some experimentations required)

**Expected behavior**
Screen sharing should share full screen.

**Screenshots**
This is a screenshot from my friend who was testing this with me. I'm sharing a screen (not a window) with gimp on it.
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/5592501/85158b1d-21b5-4b08-9d49-f008f038aa20)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: Flatpak
 - Version: 1.2.9

**Additional context**
-

**Comment by jijojosephk** [comment]
Are you on `Wayland' or `X11` ? On `X11`, you'll have additional option to choose `Quality` like `HD, FHD,2K, 4K` Can you try any of those and see if it helps?

**Comment by abobowicz** [comment]
This is on Wayland. Earlier I installed the snap version, but on that one, screen sharing doesn't work. After switching to Flatpak screen sharing started to work, but my colleague notice my current problem.

**Comment by abobowicz** [comment]
Problem have evolved. Now I can only share in proportions of my main screen (21:9). No matter what I share (screen or window) it always shares only the middle 21:9 proportion rectangle part, leaving the top and bottom black.

**Comment by abobowicz** [comment]
This problem dose not occur when using web version of ms teams.

**Comment by IsmaelMartinez** [comment]
can you check if that still happens with another package distribution ? (deb, rpm etc). This is odd.

**Comment by abobowicz** [comment]
Was testing appimage and flatpack. I'll check deb and snap as soon as I can.

**Comment by abobowicz** [comment]
Snap - cannot share the screen at all. I'm getting a "Cannot access the camera" message
Deb - Sharing screen works but the same problem. It only shows a 21:9 rectangle of shared space.

**Comment by SpyPower** [comment]
I am kinda on the same boat here, but different results.
I have three screens, under wayland, different resolutions with different orientations.
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/13405649/c71fa13c-4727-46fa-bcbd-5765e9f447b2)
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/13405649/a1e7fb4e-c64d-4ef5-8f47-fcb6d045f0af)
I have installed via deb.
When i share my horizontal screen, others see a 4:3 (approximately) resolution.
Source PC: 
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/13405649/65974feb-9ade-4caf-98a3-fd10ab65aed1)
receiver PC:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/13405649/9e414799-2787-4d92-8cff-f96e07479372)

**Comment by IsmaelMartinez** [comment]
out of curiosity, are you still trying on version 1.2.9 or are those tests in later versions? Electron changed quite a bit around 1.3.10 (or around). That might have changed this... 

Would you be able to test another screensharing (or even recording) tool that uses electron? (like this one https://github.com/alande-amorim/electron-screen-recorder - FYI, I haven't look at the code of that app nor have any relationship with alande-amorim .)

**Comment by abobowicz** [comment]
I'm using flatpack version 
teams-for-linux                                   com.github.IsmaelMartinez.teams_for_linux             1.3.19                     stable                  system

**Comment by abobowicz** [comment]
I've tried the electron screen recorder and recording a single window works fine, but when I want to record the whole screen I'm only getting black image with only my cursor, and by moving it I can say that it forces both screens on one canvas.

**Comment by SpyPower** [comment]
> out of curiosity, are you still trying on version 1.2.9 or are those tests in later versions? Electron changed quite a bit around 1.3.10 (or around). That might have changed this...
> 
> Would you be able to test another screensharing (or even recording) tool that uses electron? (like this one https://github.com/alande-amorim/electron-screen-recorder - FYI, I haven't look at the code of that app nor have any relationship with alande-amorim .)

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/13405649/6bdde53d-479a-425b-bbca-c440448c7d26)
Deb version

**Comment by qdrop17** [comment]
The issue ain't fixed with 1.4.1. I installed the RPM on Fedora 39 with Wayland.

**Comment by abobowicz** [comment]
The problem persists in 1.4.1. 
I was testing other clients and Ferdium has the same problem. Only when I use Teams from the Chromium browser does screen sharing work fine.

**Comment by Gorship** [comment]
Same issue here, only happens on wayland.

**Comment by holle** [comment]
One suggestion comes to my mind, relating to the Linux frambuffer behavior I have experienced before:
Try setting the video mode on the linux boot commandline to 80x25 (textmode) instead of using a fancy gfx mode.
Sometimes either the card or the kernel messed things up broke some video modes.

That is at least something one should be able to run really quickly...
Should be something around:
`video=...`
or
`vga=...`
(I think vga=ask worked for me back then)

Please dig around here for the parameter details:
https://docs.kernel.org/admin-guide/kernel-parameters.html

**Comment by eprudspk** [comment]
> One suggestion comes to my mind, relating to the Linux frambuffer behavior I have experienced before: Try setting the video mode on the linux boot commandline to 80x25 (textmode) instead of using a fancy gfx mode. Sometimes either the card or the kernel messed things up broke some video modes.
> 
> That is at least something one should be able to run really quickly... Should be something around: `video=...` or `vga=...` (I think vga=ask worked for me back then)
> 
> Please dig around here for the parameter details: https://docs.kernel.org/admin-guide/kernel-parameters.html

Why would anyone need to mess around with Linux kernel parameters for something that other applications have no problem doing?

**Comment by IsmaelMartinez** [comment]
Can you check 1.4.3. pre-release. The desktop sharing has changed in there.

**Comment by abobowicz** [comment]
1.4.3 fix the problem. Sharing screens and windows works fine for me :)
